{% set remote = remote_directory | default("/") %}
{% set requirements = requirements_path | default("requirements.txt") %}
{% set script = script_filename | default("exec.py") %}
{% set interpreter = python_interpreter | default("python3") %}

FROM web-executor-base
MAINTAINER Andrey Kiselev "kiselevandrew@yandex.ru"

COPY {{script}} {{remote}}/{{script}}
COPY {{requirements}} {{remote}}/{{requirements}}
RUN pip{% if interpreter == 'python3' %}3{% endif %} install -r {{remote}}/{{requirements}}

CMD ["{{interpreter}}", "{{remote}}/{{script}}"]
