# Generated by Django 2.2.2 on 2019-06-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercode',
            old_name='code_id',
            new_name='codes',
        ),
        migrations.RenameField(
            model_name='usercode',
            old_name='user_id',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='pywebuser',
            name='socials',
            field=models.CharField(blank=True, max_length=512, verbose_name='socials'),
        ),
    ]
