# Generated by Django 2.2.2 on 2019-06-30 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190619_1436'),
        ('authapp', '0002_auto_20190630_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercode',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='usercode',
            name='users',
        ),
        migrations.AddField(
            model_name='usercode',
            name='code_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.CodeBase'),
        ),
        migrations.AddField(
            model_name='usercode',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
