# Generated by Django 2.2.2 on 2019-06-30 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190701_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='code_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CodeBase'),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
