# Generated by Django 2.2.3 on 2019-08-07 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20190701_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pywebuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='proglangs',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='socials',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='userphoto',
        ),
        migrations.RemoveField(
            model_name='pywebuser',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='pywebuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='PyWebUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphoto', models.ImageField(blank=True, upload_to='userphotos')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='age')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=128, verbose_name='state')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('zipcode', models.CharField(blank=True, max_length=16, verbose_name='zipcode')),
                ('company', models.CharField(blank=True, max_length=256, verbose_name='company')),
                ('bio', models.TextField(blank=True, max_length=2048, verbose_name='bio')),
                ('socials', models.CharField(blank=True, max_length=512, verbose_name='socials')),
                ('proglangs', models.CharField(blank=True, max_length=512, verbose_name='programming languages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
