# Generated by Django 2.2.4 on 2019-08-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_container_last_access_at'),
        ('authapp', '0007_auto_20190818_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercode',
            unique_together={('user', 'code')},
        ),
    ]
