# Generated by Django 2.2.2 on 2019-06-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=2048, verbose_name='Code text')),
                ('is_errors', models.BooleanField(default=False, verbose_name='Errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': "User's code",
                'verbose_name_plural': "User's code",
            },
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=2048, verbose_name='Code execution result')),
                ('profile', models.CharField(max_length=2048, verbose_name='Code profile result')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='mainapp.CodeBase')),
            ],
            options={
                'verbose_name': "User's code result",
                'verbose_name_plural': "User's code results",
            },
        ),
    ]
