# Generated by Django 2.2.2 on 2019-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190618_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexecution',
            name='has_errors',
            field=models.BooleanField(default=False, verbose_name='Does code have errors?'),
        ),
        migrations.AlterField(
            model_name='codeexecution',
            name='profile',
            field=models.CharField(default=None, max_length=2048, null=True, verbose_name='Code profile result'),
        ),
    ]
