# Generated by Django 2.2.2 on 2019-06-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190618_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexecution',
            name='id',
        ),
        migrations.AlterField(
            model_name='codeexecution',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.CodeBase'),
        ),
    ]
