# Generated by Django 2.2.2 on 2019-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190626_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Container ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
            ],
            options={
                'verbose_name': 'Container information',
                'verbose_name_plural': 'Containers information',
            },
        ),
    ]
