# Generated by Django 2.2.2 on 2019-07-04 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='last_access_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
